export default [
  {
    batch: 12,
    day: "Sunday",
    first: "CSE-3213",
    second: "HUM-3261",
    third: "CSE-3213",
    fourth: "HUM-3259",
    fifth: "",
    sixth: "",
  },
  {
    batch: 12,
    day: "Monday",
    first: "CSE-3212",
    second: "remains",
    third: "remains",
    fourth: "CSE-3215",
    fifth: "HUM-3259",
    sixth: "HUM-3261",
  },
  {
    batch: 12,
    day: "Tuesday",
    first: "CSE-3213",
    second: "",
    third: "CSE-3215",
    fourth: "CSE-3211",
    fifth: "CSE-3211",
    sixth: "HUM-3259",
  },
  {
    batch: 12,
    day: "Wednesday",
    first: "CSE-3216",
    second: "remains",
    third: "remains",
    fourth: "CSE-3222",
    fifth: "remains",
    sixth: "remains",
  },
  {
    batch: 12,
    day: "Thursday",
    first: "CSE-3200",
    second: "remains",
    third: "remains",
    fourth: "CSE-3211",
    fifth: "CSE-3215",
    sixth: "",
  },
];
