export default [
  {
    batch: 13,
    day: "Sunday",
    first: "",
    second: "CSE-4103",
    third: "remains",
    fourth: "MATH-4107",
    fifth: "CSE-4000",
    sixth: "remains",
  },
  {
    batch: 13,
    day: "Monday",
    first: "CSE-4104",
    second: "remains",
    third: "remains",
    fourth: "CSE-4101",
    fifth: "HUM-4163",
    sixth: "CSE-4103",
  },
  {
    batch: 13,
    day: "Tuesday",
    first: "CSE-4101",
    second: "remains",
    third: "MATH-4107",
    fourth: "CSE-4102",
    fifth: "remains",
    sixth: "remains",
  },
  {
    batch: 13,
    day: "Wednesday",
    first: "CSE-4137",
    second: "remians",
    third: "remains",
    fourth: "MATH-4107",
    fifth: "",
    sixth: "CSE-4000",
  },
  {
    batch: 13,
    day: "Thursday",
    first: "CSE-4100",
    second: "remains",
    third: "remians",
    fourth: "HUM-4163",
    fifth: "remians",
    sixth: "",
  },
];
