export default [
  {
    day: "Sunday",
    time_1: false,
    time_2: false,
    time_3: false,
    time_4: false,
    time_5: false,
    time_6: false,
  },
  {
    day: "Monday",
    time_1: false,
    time_2: false,
    time_3: false,
    time_4: false,
    time_5: false,
    time_6: false,
  },
  {
    day: "Tuesday",
    time_1: false,
    time_2: false,
    time_3: false,
    time_4: false,
    time_5: false,
    time_6: false,
  },
  {
    day: "Wednesday",
    time_1: false,
    time_2: false,
    time_3: false,
    time_4: false,
    time_5: false,
    time_6: false,
  },
  {
    day: "Thursday",
    time_1: false,
    time_2: false,
    time_3: false,
    time_4: false,
    time_5: false,
    time_6: false,
  },
];
